services:
  backend:
    image: registry.snappfood.ir/platform/pantheon/parkingapi:latest
    ports:
      - "5025:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Server=mysql;Port=3306;Database=parking;User=root;Password=${MYSQL_PASSWORD};

  frontend:
    image: registry.snappfood.ir/platform/pantheon/parkingweb:latest
    ports:
      - "5026:80"
    depends_on:
      - backend
