services:
  backend:
    build: Parking.API
    ports:
      - "5025:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - parking-data:/data

  frontend:
    build: parking-ui
    ports:
      - "5026:80"
    depends_on:
      - backend

volumes:
  parking-data:
